name: challenge

on: push

jobs:
  ubuntu: 
   runs-on: ubuntu-latest
   steps:
    - name: step1
      run: date

    - name: step2
      uses: actions/checkout@v3

  windows:
   runs-on: windows-latest
   steps:
    - run: date

  macos: 
   runs-on: macos-latest
   steps:
    - run: date

  dependence: 
   runs-on: ubuntu-latest
   needs: [ubuntu, windows, macos]      
   steps: 
      - uses: actions/checkout@v3
    

