name: challenge

on: push

jobs:
  ubuntu: 
   runs-on: ubuntu-latest
   steps:
    - name: step1
      run: date

    - name: step2
      uses: actions/checkout@v3
    - name: Python Syntax Checker
  # You may pin to the exact commit or the version.
  # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

  windows:
   runs-on: windows-latest
   steps:
    - run: date

  macos: 
   runs-on: macos-latest
   steps:
    - run: date

  dependence: 
   runs-on: ubuntu-latest
   needs: [ubuntu, windows, macos]      
   steps: 
      - uses: actions/checkout@v3
    

